export { AboutMe } from './about/about'
export { Socials } from './Socials/Socials'
export { CustomDivider } from './Divider/Divider'
export { Navbar } from './navbar/navbar'
export { Skills } from './skills/skills'
export { Introduction } from './introduction/introduction'
export { Projects } from './projects/projects'
export { ContactMe } from './contact/contact'
